import dayjs from "dayjs";

const PrintFooter = ({
  generatedBy = "Money Services System",
}) => {
  return (
    <div className="mt-10 border-t border-gray-300 pt-4 flex justify-between items-center text-xs text-gray-500">

      <div>
        Generated by <strong>{generatedBy}</strong>
      </div>

      <div>
        Printed on {dayjs().format("DD MMM YYYY hh:mm A")}
      </div>

    </div>
  );
};

export default PrintFooter;